name: TeXtidote
on: push
jobs:
  TeXtidote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ChiefGokhlayeh/textidote-action@v5
        id: textidote
        with:
          root_file: src/main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: report.html
      - name: Fail
        if: ${{ steps.textidote.outputs.num_warnings != 0 }}
        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
